<a href="https://colab.research.google.com/github/NohaWaly/Bootstrap-Project/blob/master/Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
! git clone https://github.com/ardamavi/Sign-Language-Digits-Dataset.git

fatal: destination path 'Sign-Language-Digits-Dataset' already exists and is not an empty directory.


In [75]:
import numpy as np
import matplotlib.pyplot as plt
#cv2 to read image, show and more
import cv2
import os
import random
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from keras import layers
from keras import models as ml
from keras import optimizers
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
from numpy import argmax

DataDir = "Sign-Language-Digits-Dataset/Dataset"
ImgSize = 100

Categories = ["0", "1","2","3", "4","5","6", "7","8","9"]
data = []
#iterate over 10 folders
for category in Categories:  
    # create path to each gesture 
    path = os.path.join(DataDir,category) 
    classNum = Categories.index(category)
    #print(path)
    # iterate over each image per each gesture 
    for img in os.listdir(path): 
        print(img)
        # convert to array
        img_array = cv2.imread(os.path.join(path,img) ,cv2.IMREAD_COLOR) 
        # resize data
        resize_array = cv2.resize(img_array, (ImgSize, ImgSize))
        #append to data
        data.append([resize_array, classNum])
        # graph it
        #plt.imshow(img_array)
        # display!   
        #plt.show()  


IMG_5635.JPG
IMG_4796.JPG
IMG_5380.JPG
IMG_5028.JPG
IMG_4139.JPG
IMG_5318.JPG
IMG_4296.JPG
IMG_5847.JPG
IMG_4574.JPG
IMG_4476.JPG
IMG_5857.JPG
IMG_5625.JPG
IMG_4316.JPG
IMG_4456.JPG
IMG_4348.JPG
IMG_4181.JPG
IMG_4684.JPG
IMG_4604.JPG
IMG_1148.JPG
IMG_4836.JPG
IMG_4856.JPG
IMG_1270.JPG
IMG_4846.JPG
IMG_5655.JPG
IMG_5341.JPG
IMG_4109.JPG
IMG_5446.JPG
IMG_4776.JPG
IMG_5786.JPG
IMG_5756.JPG
IMG_5675.JPG
IMG_4223.JPG
IMG_4423.JPG
IMG_5350.JPG
IMG_4564.JPG
IMG_4976.JPG
IMG_4233.JPG
IMG_4338.JPG
IMG_1209.JPG
IMG_5053.JPG
IMG_4435.JPG
IMG_1179.JPG
IMG_1260.JPG
IMG_5466.JPG
IMG_5101.JPG
IMG_1280.JPG
IMG_5645.JPG
IMG_5776.JPG
IMG_4725.JPG
IMG_5981.JPG
IMG_5063.JPG
IMG_4193.JPG
IMG_5193.JPG
IMG_4956.JPG
IMG_4506.JPG
IMG_4624.JPG
IMG_4694.JPG
IMG_5928.JPG
IMG_4276.JPG
IMG_4807.JPG
IMG_4966.JPG
IMG_5517.JPG
IMG_5297.JPG
IMG_4119.JPG
IMG_4876.JPG
IMG_4413.JPG
IMG_1118.JPG
IMG_4243.JPG
IMG_4079.JPG
IMG_4149.JPG
IMG_4634.JPG
IMG_5572.JPG
IMG_5562.JPG
IMG_5867.JPG
IMG_5736.JPG
IMG_4554.JPG
IMG_1169.JPG

In [0]:
#shuffle data (msh kol class ykon wara b3d)
random.shuffle(data)  
#print(data)


In [77]:
X = []
y = []

for features, label in data:
   X.append(features)
   y.append(label)
#to enter the model it should be np array
X = np.array(X)
y = np.array(y,dtype=int)

#hot incoder
y = to_categorical(y)

print(X)
print(y)

[[[[138 133 134]
   [138 133 134]
   [140 135 136]
   ...
   [146 136 136]
   [145 135 135]
   [144 134 134]]

  [[138 133 134]
   [139 134 135]
   [140 135 136]
   ...
   [147 137 137]
   [145 135 135]
   [144 134 134]]

  [[139 134 135]
   [140 135 136]
   [141 136 137]
   ...
   [148 138 138]
   [146 136 136]
   [145 135 135]]

  ...

  [[119 121 121]
   [120 122 122]
   [124 124 124]
   ...
   [121 117 116]
   [119 115 114]
   [118 114 113]]

  [[118 120 120]
   [119 121 121]
   [123 123 123]
   ...
   [119 116 112]
   [117 114 110]
   [116 113 109]]

  [[117 119 119]
   [119 121 121]
   [122 122 122]
   ...
   [117 114 110]
   [116 113 109]
   [115 112 108]]]


 [[[125 127 128]
   [128 130 131]
   [132 131 133]
   ...
   [129 128 130]
   [127 126 128]
   [125 124 126]]

  [[125 127 128]
   [129 131 132]
   [133 132 134]
   ...
   [130 129 131]
   [128 127 129]
   [126 125 127]]

  [[127 129 130]
   [130 132 133]
   [134 133 135]
   ...
   [132 131 133]
   [130 129 131]
   [128 127

In [78]:
#normalization of data
#get mean of index 3 of shape =>3 layers
mean_array = np.mean(X, axis=3)
print(mean_array.shape)
mean_array = np.expand_dims(mean_array, axis=3)
print(mean_array.shape)
Xnormalized = (X - mean_array)/255.0
print(Xnormalized)

(2062, 100, 100)
(2062, 100, 100, 1)
[[[[ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   ...
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]]

  [[ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   ...
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]]

  [[ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   [ 0.01176471 -0.00784314 -0.00392157]
   ...
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]
   [ 0.02614379 -0.0130719  -0.0130719 ]]

  ...

  [[-0.00522876  0.00261438  0.00261438]
   [-0.00522876  0.00261438  0.00261438]
   [ 0.          0.          0.        ]
   ...
   [ 0.01176471 -0.00392157 -0.00784314]
   [ 0.01176471 -0.0

In [79]:
Xnormalized.shape

(2062, 100, 100, 3)

In [0]:
       
#spliting training & test sets
X_train, X_test, y_train, y_test = train_test_split(Xnormalized,y,test_size=0.2, random_state=7)

In [0]:

def create_cnn_model1():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(128, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model2():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(128, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model3():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.MaxPooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
def create_cnn_model4():
    model = ml.Sequential()
    #32 filters, thier size 3*3
    model.add(layers.Conv2D(32, (3, 3), activation='relu',input_shape=(100, 100, 3)))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Conv2D(64, (3, 3), activation='relu'))
    model.add(layers.AveragePooling2D((2, 2)))
    model.add(layers.Flatten())
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(loss='categorical_crossentropy',optimizer = tf.train.AdamOptimizer(),metrics=['acc'])
    return model

In [0]:
n_split = 4
val_loss = np.zeros(n_split)
val_acc = np.zeros(n_split)

k_Fold = KFold(n_splits=4)
modeling = [create_cnn_model1,create_cnn_model2,create_cnn_model3,create_cnn_model4]
for x in range(4):
  i=0
  for train, validate in k_Fold.split(X_train, y_train):
    model = modeling[x]()
    model.fit(X_train[train], y_train[train], epochs=50)
    val_loss[i], val_acc[i] = model.evaluate(X_train[validate],y_train[validate])
    model.summary()
    i+=1
  print("Average Loss and Accuracy in Architecture" +str(x+1))
  print(val_loss.mean())
  print(val_acc.mean()) 
    #evaluate the testing part
  print("Evaluate testing part")
  model.evaluate(X_test, y_test)
  #get predicted labels
  y_predict = model.predict_classes(X_test)
  #reverse from categorial 
  y_test = np.argmax(y_test, axis=1, out=None)
  #evaluate model using precision, fscore, & recall
  print(classification_report(y_test, y_predict, target_names=Categories))

Epoch 1/50
1236/1236 [==============================] - 4s 3ms/step - loss: 1.7173 - acc: 0.4061
Epoch 2/50
1236/1236 [==============================] - 0s 374us/step - loss: 0.7958 - acc: 0.7435
Epoch 3/50
1236/1236 [==============================] - 0s 369us/step - loss: 0.5613 - acc: 0.8301
Epoch 4/50
1236/1236 [==============================] - 0s 385us/step - loss: 0.4238 - acc: 0.8697
Epoch 5/50
1236/1236 [==============================] - 0s 361us/step - loss: 0.3260 - acc: 0.9013
Epoch 6/50
1236/1236 [==============================] - 0s 373us/step - loss: 0.2417 - acc: 0.9183
Epoch 7/50
1236/1236 [==============================] - 0s 377us/step - loss: 0.1671 - acc: 0.9466
Epoch 8/50
1236/1236 [==============================] - 0s 367us/step - loss: 0.1131 - acc: 0.9620
Epoch 9/50
1236/1236 [==============================] - 0s 361us/step - loss: 0.0891 - acc: 0.9773
Epoch 10/50
1236/1236 [==============================] - 0s 371us/step - loss: 0.0715 - acc: 0.9830
Epoch 11/50